include:
- ./functions/search-vic-crime-by-area.zip
kind: ArchiveUploadSpec
name: functions-search-vic-crime-by-area-zip-eRFI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-vic-crime-by-area
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-vic-crime-by-area-zip-eRFI
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T16:07:18Z"
