include:
- ./functions/search-vic-crime-by-offence-count.zip
kind: ArchiveUploadSpec
name: functions-search-vic-crime-by-offence-count-zip-k7uw

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-vic-crime-by-offence-count
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-vic-crime-by-offence-count-zip-k7uw
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T09:38:23Z"
