include:
- ./functions/search-vic-crimegov.zip
kind: ArchiveUploadSpec
name: functions-search-vic-crimegov-zip-qYhy

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-vic-crimegov
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-vic-crimegov-zip-qYhy
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T09:27:30Z"
