include:
- ./functions/search-viccrime-for-twitter.zip
kind: ArchiveUploadSpec
name: functions-search-viccrime-for-twitter-zip-NgQE

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-viccrime-for-twitter
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-viccrime-for-twitter-zip-NgQE
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T09:39:20Z"
