include:
- ./functions/search-twitter-busiestday.zip
kind: ArchiveUploadSpec
name: functions-search-twitter-busiestday-zip-3PpW

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-twitter-busiestday
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-twitter-busiestday-zip-3PpW
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T08:17:52Z"
