include:
- ./functions/searchmharvester.zip
kind: ArchiveUploadSpec
name: functions-searchmharvester-zip-xrbZ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: searchmharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-searchmharvester-zip-xrbZ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T08:53:25Z"
