include:
- ./functions/search-twitter-daily-tweets.zip
kind: ArchiveUploadSpec
name: functions-search-twitter-daily-tweets-zip-suMI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-twitter-daily-tweets
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-twitter-daily-tweets-zip-suMI
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T09:19:48Z"
