include:
- ./functions/aprocessor.js
kind: ArchiveUploadSpec
name: functions-aprocessor-js-uLJo

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: aprocessor-5e97a0ee-d039-46d1-8e07-8797d3af40be
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-aprocessor-js-uLJo
  environment:
    name: nodejs
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-09T17:31:57Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: aprocessor
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodejs
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: aprocessor-5e97a0ee-d039-46d1-8e07-8797d3af40be
      namespace: ""
  requestsPerPod: 1
  resources: {}
