include:
- ./functions/healthcm.py
kind: ArchiveUploadSpec
name: functions-healthcm-py-uKCY

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: healthcm-92fc0fd9-a06d-41d1-b374-7c3defb7b0a3
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-healthcm-py-uKCY
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-09T17:29:36Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: healthcm
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: shared-data
    namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: healthcm-92fc0fd9-a06d-41d1-b374-7c3defb7b0a3
      namespace: ""
  requestsPerPod: 1
  resources: {}
