include:
- ./functions/wharvester.py
kind: ArchiveUploadSpec
name: functions-wharvester-py-vMB8

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wharvester-a3e70111-86fd-4fcd-985a-d56ecd7761a2
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-wharvester-py-vMB8
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-09T17:31:57Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wharvester
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: wharvester-a3e70111-86fd-4fcd-985a-d56ecd7761a2
      namespace: ""
  requestsPerPod: 1
  resources: {}
