include:
- ./functions/mprocessor.js
kind: ArchiveUploadSpec
name: functions-mprocessor-js-ywLm

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mprocessor-bf60590c-eb15-4170-955a-796830745f1c
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-mprocessor-js-ywLm
  environment:
    name: nodejs
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-15T03:39:28Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: mprocessor
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodejs
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: mprocessor-bf60590c-eb15-4170-955a-796830745f1c
      namespace: ""
  requestsPerPod: 1
  resources: {}
