include:
- ./functions/health.py
kind: ArchiveUploadSpec
name: functions-health-py-dPlU

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: health-fa19d866-6925-415d-aa66-082fa55f3d33
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-health-py-dPlU
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-09T17:26:45Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: health
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: health-fa19d866-6925-415d-aa66-082fa55f3d33
      namespace: ""
  requestsPerPod: 1
  resources: {}
