include:
- ./functions/mharvester.zip
kind: ArchiveUploadSpec
name: functions-mharvester-zip-6PpU

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-mharvester-zip-6PpU
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T15:43:48Z"
