include:
- ./functions/search-twitter-quietestday.zip
kind: ArchiveUploadSpec
name: functions-search-twitter-quietestday-zip-8dTi

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-twitter-quietestday
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-twitter-quietestday-zip-8dTi
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-18T09:30:09Z"
