include:
- ./functions/enqueue.zip
kind: ArchiveUploadSpec
name: functions-enqueue-zip-Tqg0

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: enqueue
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-enqueue-zip-Tqg0
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T01:56:12Z"
