include:
- ./functions/search-south-crimegov.zip
kind: ArchiveUploadSpec
name: functions-search-south-crimegov-zip-DuVS

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-south-crimegov
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-south-crimegov-zip-DuVS
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T15:19:09Z"
