include:
- ./functions/enqueue.zip
kind: ArchiveUploadSpec
name: functions-enqueue-zip-wje2

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: enqueue
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-enqueue-zip-wje2
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-14T05:08:27Z"
