include:
- ./functions/addobservations.zip
kind: ArchiveUploadSpec
name: functions-addobservations-zip-4448

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addobservations
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-addobservations-zip-4448
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-09T17:43:16Z"
