include:
- ./functions/deletemharvester.zip
kind: ArchiveUploadSpec
name: functions-deletemharvester-zip-l57G

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: deletemharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-deletemharvester-zip-l57G
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T16:16:51Z"
