include:
- ./functions/addmastodon.zip
kind: ArchiveUploadSpec
name: functions-addmastodon-zip-zJw9

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addmastodon
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-addmastodon-zip-zJw9
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T01:59:41Z"
