include:
- ./functions/search-vic-population.zip
kind: ArchiveUploadSpec
name: functions-search-vic-population-zip-KxwX

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search-vic-population
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-vic-population-zip-KxwX
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T09:05:52Z"
