include:
- ./functions/mharvester.zip
kind: ArchiveUploadSpec
name: functions-mharvester-zip-Nm6f

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-mharvester-zip-Nm6f
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-14T18:07:15Z"
