apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: search-vic-crime-by-offence-count
spec:
  createingress: true
  functionref:
    functionweights: null
    name: search-vic-crime-by-offence-count
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /search-vic-crime-by-offence-count
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /search-vic-crime-by-offence-count
