apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: searchmharvester-with-size
spec:
  createingress: true
  functionref:
    functionweights: null
    name: searchmharvester
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /mastodon/{size}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /mastodon/{size}
